project:
  type: website
  output-dir: docs

website:
  title: ""
  page-footer:
    center: "[![](https://raw.githubusercontent.com/heatcordoba/heatcordoba.github.io/refs/heads/main/img/org/conae-2.png){width=80}](https://www.argentina.gob.ar/ciencia/conae) &nbsp;&nbsp;&nbsp;&nbsp; [![](https://raw.githubusercontent.com/heatcordoba/heatcordoba.github.io/refs/heads/main/img/org/ig-2.png){width=120}](https://ig.conae.unc.edu.ar/) [![](https://raw.githubusercontent.com/heatcordoba/heatcordoba.github.io/refs/heads/main/img/org/esa-2.png){width=100}](https://www.esa.int/) [![](https://raw.githubusercontent.com/heatcordoba/heatcordoba.github.io/refs/heads/main/img/org/future-earth-2.png){width=120}](https://futureearth.org/) &nbsp;&nbsp; [![](https://raw.githubusercontent.com/heatcordoba/heatcordoba.github.io/refs/heads/main/img/org/pavia-2.png){width=50}](https://portale.unipv.it/it)"
  navbar: 
    left:
      - href: water.qmd
        text: "{{< iconify ion:water >}} Water quality"
      - href: urban.qmd
        text: "{{< iconify mdi:heat-index >}} Urban Heat Island"
      - href: aedes.qmd
        text: "{{< iconify fluent-emoji-high-contrast:mosquito >}} Aedes aegypti mosquito" 
      - href: about.qmd
        text: "{{< iconify ri:team-fill >}} Team"
      - text: "{{< iconify mdi:pen >}} Outcomes"
        menu:
          - href: outcomes/reports.qmd
            text: "{{< iconify boxicons:file-report >}} Reports"
          - href: outcomes/academic.qmd
            text: "{{< iconify mingcute:paper-fill >}} Academic publications"
          - href: outcomes/media.qmd
            text: "{{< iconify material-symbols:tv-outline >}} Heat Córdoba on media"
          - href: outcomes/workshops.qmd
            text: "{{< iconify qlementine-icons:education-16 >}} Workshop"
          - href: outcomes/education.qmd
            text: "{{< iconify fa7-solid:university >}} Education resources"
          - href: outcomes/campaigns.qmd
            text: "{{< iconify game-icons:paper-boat >}} Field campaigns"
    foreground: "white"
    tools:
        - icon: github
          href: "https://github.com/heatcordoba/heatcordoba.github.io"
          target: _blank
  favicon: img/isotipos/POSITIVO TRANSPARENTE.png
  open-graph: 
    site-name: Heat Córdoba
  repo-url: https://github.com/heatcordoba/heatcordoba.github.io
  repo-actions: [edit, source, issue]
  back-to-top-navigation: true
  
format:
  html:
    theme:
      light: 
        - flatly
        - extras/estilo.scss
        - extras/estilo_light.scss
      dark: 
        - darkly
        - extras/estilo.scss
        - extras/estilo_dark.scss
    respect-user-color-scheme: true
    toc: true
    toc-title: "Content"
    page-layout: full
    link-external-newwindow: true
    crossrefs-hover: false
    grid:
    #   sidebar-width: 300px
    #   body-width: 900px
      margin-width: 350px
    #   gutter-width: 1.5rem
    
execute:
  freeze: auto
  echo: false
  eval: true
  warning: false

editor_options: 
  chunk_output_type: console
