---
title: "<titulo>Heat Córdoba</titulo>"
subtitle: "Heat waves impact on urban population: a South American case in the climate change context"
logo: medium
abstract: "Heatwaves (HW) involve extended periods of abnormal heat, which differ across populations based on social and environmental factors.  The impacts of HW on cities have been studied and described mainly in the Northern Hemisphere, but little has been done in the global South. An exploratory analysis of the frequency of HW using Copernicus Era5 Land data is already underway in Argentina, although the impacts of HW have not been studied yet. In this proposal, Córdoba City, the second most populated in Argentina, is selected to evaluate HW impacts on urban areas. Copernicus CCS data and Sentinel-3- SLSTR products will be used to characterize heatwave impacts on urban population and infrastructure, vector-borne diseases, and water quality of the drinking water supply. Environmental and LULC (Land Use/Land Cover) products, derived from ESA Sentinel missions, will be integrated with socioeconomic local data to develop hazards and vulnerability maps. Specifically, the impact of HW on the urban heat island effect (UHI), the activity of Aedes aegypti mosquitoes (vectors of dengue virus), and the occurrence of episodes of bad smell and taste related to cyanobacteria blooms in the main water reservoirs will be evaluated and quantified as the “hazards”. The models accounting for the vulnerability factor will include socioeconomic and infrastructure variables. Based on the vulnerable population, HW risk maps will be generated and results will be available to the scientific community, including social scientists, the general public, and stakeholders through dissemination and communication activities, including publication in a Web GIS platform."
format:
  html:
    other-links:
      - text: Access to visualize and download maps
        href: https://www.google.com/
        icon: arrow-up-right-circle-fill
bibliography: biblio/bibliografia.bib
csl: biblio/ieee.csl
---

# Problem statement

Global warming is affecting life on our planet, providing new dynamic equilibrium states with unprecedented consequences on ecosystems and human health @abdul2025climate. The global scientific community unanimously agrees that climate change is leading to a rise in the frequency of extreme weather events such as floods, droughts, tornadoes, and heat and cold waves. Impacts of global warming extend beyond environmental changes to include economic and social dimensions, where vulnerability consideration is crucial to assess risks for humans @bashmakov2022climate. While heat waves are silent compared to other extreme weather events, they significantly increase energy consumption in urban areas and pose serious risks to human health, such as dehydration or illness caused by waterborne or vector-borne diseases. Heat waves are characterized by prolonged periods of abnormal heat. Their impact varies widely among different populations due to factors such as age, socioeconomic status, and local environments like urban heat islands (UHI). This has led to the absence of a universal standard for defining and grading heat waves. In the case of South America, there is no operational system to monitor heat waves yet, and their spatial and temporal characterization in this region is necessary to develop early warning systems and response/mitigation strategies, especially in urban areas. To develop such systems and strategies, we need to understand the impact of heat waves on UHI, vector and water-borne disease outbreaks, and vulnerable populations, among other things. Remote sensing offers global, robust, and scalable data and methods to monitor both heat waves and some of their effects @Montillet2024.

More than 201 Earth observation satellite missions from different space agencies are operative and collecting valuable information to tackle surface and atmospheric changes with high spatial, temporal, and spectral resolution. In the era of this globally distributed and high-quality satellite information, climate change impact characterization at urban scales has become feasible. Nevertheless, a few studies regarding the terms “Heatwaves” and “UHI” show a vacancy area in relating heatwaves and their local effects on UHI, specifically in South America. Only a few works were done to characterize UHI for urban cities in  Argentina , Perú, and Chile, but none of them show the effect of heatwaves on UHI. In addition, the effects of HW on vector-borne diseases, such as Dengue, and waterborne diseases are poorly described. The importance of UHI lies in its effect on biodiversity and its alteration of local urban ecosystems. Particularly, temperature affects different life traits of Ae. aegypti, their development time and survival, fecundity, oviposition and flight activity, with consequences on the speed of pathogen replication and further transmission to humans. Suitability maps for mosquitoes have been generated for Córdoba previously by our work group . It has been reported, however, that the configuration of trees and impervious surfaces within urban areas play a fundamental role in the UHI effects. Exploring such configurations and local temperature variations is crucial in areas where Ae. aegypti is present. 

Finally, it is well known that global warming is facilitating harmful algal blooms occurrence globally, mainly in highly urbanized basins, causing episodes of bad smell and taste,  increasing the risk to human health due to the release of toxins and elevating the purification costs for water supply. Although the effect of HW on water quality was studied in Europe and other regions it has not been characterized in South America yet. San Roque reservoir, the main source of water supply of Córdoba city,  provides 70 % of the city's potable  water (almost 2 million people). The lake presents recurrent harmful algal blooms, which have been characterized by EO data in recent years. However, they have not been linked to the occurrence of HW, nor have they had a more detailed impact based on the vulnerable infrastructure of the inhabitants who depend on this water supply.

# Science plan

## Main Objective

The main objective of this proposal is to advance our understanding of heatwave impacts on urban areas, focusing on vulnerable urban infrastructure, vector-borne disease outbreaks, and intake water quality  using a risk model framework.

## Specific Objectives

SO1-Characterize the spatio-temporal distribution of heatwaves in Córdoba city and surroundings. 
SO2- Characterize the seasonal UHI behaviour in Córdoba city.
SO3- Evaluate heatwaves/UHI impacts on vulnerable infrastructures of the city (slums).
SO4- Evaluate heatwaves/UHI impacts on the activity of Aedes aegypti in the City.
SO5- Evaluate heatwaves' impact on Cordoba water supply quality.

## Study area

The study area is the city of Córdoba and its surroundings. Córdoba is located in central Argentina and it is the second most populated city, after Buenos Aires, and the largest in extension. It has 1,505,250 inhabitants (2613,3 inhabitants/km2) and more than 400000 in its northwest metropolitan region. This city is located in a temperate region of Argentina characterized by four distinct seasons, hot summers and dry winters. Annual precipitation ranges between 600 and 1000 mm, mostly concentrated from December to February. The warm and rainy period of the year spans from October to April, with average maximum and minimum temperatures of 28.59°C and 16.26°C, respectively. During the cold and dry period, average maximum and minimum temperatures range around 20.8°C and 7.84°C (SMN, 2020). There are 421 official neighbourhoods, which present different kinds of infrastructure and vulnerability depending on socio-economic variables7. The San Roque lake (central coordinates: 31o 22´ 56" S, 64o 27' 56" W) is the main source of drinking water for the city of Cordoba, and it is also used for energy generation and tourist purposes. It has a single emissary, the Suquía River, that continues and crosses the city of Cordoba. The water surface of the reservoir is 1500 Ha, which can vary according to its level. Its high level of eutrophication is a severe problem, mainly during hot summers and low winds, and given this critical situation Córdoba province was requested to immediately implement a prevention and mitigation  action protocol.  

## Methodology

In this subsection, the methodology to achieve each specific objective is presented as work packages to be developed (WP).

<u>WP1-Generate a temporal series of heatwaves</u>:  In a previous project, our group developed a temporal series of heatwaves for the whole of Argentina by analyzing the ERAS-Land air temperature product (a freely available reanalysis product from the Copernicus Program)17. We have used R open-source software for daily temperature data, until 2022 and we could identify the extreme temperature anomalies by calculating the 90th percentile on both minimum and maximum daily temperatures and determining heatwaves that impacted Argentina over the last 30 years. In this project, we will extend the time series to 2025 and we will analyze in detail Córdoba City and its surrounding heatwave patterns for the period 1995-2025.

<u>WP2- Develop and compare UHI maps for Córdoba</u>: Landsat 8 thermal bands will be used to build UHI maps. To refine the starting spatial scale (30m),  products in  the  U-TEP platform (https://urban-tep.eu/#!pages/dataservices) or the Earth sustainable cities database  (https://eotoolkit.unhabitat.org/pages/eo-data), will be considered. The temperature difference between forested and impervious areas (SUHI) will be generated to compare city temperatures variations among years and heat waves episodes6.  Day and night UHI differences will be calculated through AQUA-MODIS data, which passes during the day at 1:30 pm (near the hottest hours) and 1:30 am (near the coolest hours) to evaluate interannual,  seasonal behaviour and spatial patterns for a spatial resolution of 1 km. MODIS data will be downloaded from AppEEARS - NASA application (https://appeears.earthdatacloud.nasa.gov/).

<u>WP3-Heatwaves/SUHI impact evaluation on neighbors of the city</u>: To evaluate heatwaves/SUHI impacts on Córdoba City, a risk model based on the product of vulnerability and hazard will be implemented. First, a heatwave/SUHI hazard map will be developed by combining the spatio-temporal occurrence of heatwaves with the temporally average SUHI, named Urban thermal field variance index (UTFVI), to quantitatively describe the urban heat island effect. This approach has just been implemented for Córdoba City, but without taking into account the heatwave phenomenon7. In this line, we will also consider a new vulnerable map based on “infrastructure”, that was not taken into account in previous works. For this, we will use an official database of “slums” located in Córdoba City and its surroundings and we will calculate temperature differences concerning other urbanized zones obtained from ESA world cover data (https://worldcover2021.esa.int/). The slums database will be extracted from https://www.argentina.gob.ar/desarrollosocial/renabap/tabla. 

<u>WP4 Evaluate heat waves impact on the activity of Aedes aegypti in the city</u>: To deeply relate the impact or effect of urban land cover, temperature variation and Aedes aegypti activity within Córodba city, classifications of optical images of resolution equal to or less than 10 m obtained from Sentinel 2 or other products from ESA Urban TEP or Earth sustainable cities (e.g., the GHSL Data Package 2023) will be explored. Specific land use classes will be considered, such as recent urbanizations (gated communities), marginal urbanizations (slums), vacant lots, parks and green spaces, soccer fields, as well as peri-urban or disordered vegetation. These classes and other products will be associated with temperature indices in order to know which ones of them are potentially associated with A. aegypti activity in Cordoba. The contribution/effect of land use classes on the indices related to temperature will be evaluated by means of regression models, with mosquito field data as the dependent variable*. To this aim, different landscape metrics will be used: percent coverages, patch size, cover continuity indices, and context. Other machine learning methods, such as Random Forest, will be used to obtain/compare mosquito activity prediction.

<u>WP5-Evaluate heatwaves impact on Cordoba water supply quality</u>: Chlorophyll-a from RS data is a proxy of algae and cyanobacteria development and can be used to infer water quality. At San Roque reservoir, a customized validated algorithm, developed by the work group will be applied to the surface reflectance of Sentinel 2-MSI bands16 for the period 2015-2025 (Copernicus land service, <https://scihub.copernicus.eu/>). This model was built with a robust method that combined empirical modeling of chlorophyll-a concentration measured in situ and the NIR and RED bands of Sentinel 2-MSI, obtaining a significant fit (R<sup>2</sup> = 0.77). It was also validated with field data collected jointly with the Hydric Resources Secretary of Córdoba province. A temporal and spatial database with the date of blooms and their main features (area/intensity) will be generated. Advanced time series analysis and Fourier transform calculation will be carried out to investigate the relationships between heat waves and algae bloom occurrence to quantitatively evaluate their impacts on water quality.   During the project, the workgroup will go monthly to the reservoir to check the validity of the algorithms in time, and to collect water quality data such as: chlorophyll-a, pH, alkalinity, temperature, conductivity, suspended solids, total phosphorus, and total nitrogen.  This task will be done jointly with the Hydric Resource Secretary of Córdoba since they provide the logistics and are one of the end users of the developed products. Risk maps will be developed for the urban population taking into account the vulnerable map based on “infrastructure”  (WP3) and the neighbors of the city that are located next to the Suquia River, the emissary of San  Roque, and those that take fresh water sanitized from raw San Roque water.

<u>WP6-Communication and Dissemination</u>: The maps and knowledge generated during the project will be disseminated through different channels, i.e., in a WEB-GIS platform, scientific publications, conferences, postgraduate courses, and a public workshop held jointly with the provincial government with public officials health, ESA agents,  Future Earth members (Urban KAN and Water futures), Ibero-American Network of Health Law, Pavia University, UNESCO CHAIR in Human Segurity and Regional Development of  Blas Pascal University and Gulich Institute.  In the Expected Outcome section, the deliverables of this package are explained in detail. 


[Access to visualize and download maps](https://www.google.com/)

# References

::: {#refs}
:::
